### ISSUE TITLE
Numbered lists not legible

### ISSUE THREAD

**Issue by jaker-dotcom** [PatrickDeVries/logseq-plugin-colored-threads#16]
Hey there,
just switched over and am happy to replace bullet threading with this more visual appealing option.
However I notice, that numbered lists are not very legible, especially in (default) light theme. 
Could it be adjusted such that the numbers themselves instead of the background is coloured?

![image](https://github.com/PatrickDeVries/logseq-plugin-colored-threads/assets/74203207/f6fb1a9a-76f8-442f-81d8-04d34e8b8557)

**Comment by jaker-dotcom** [comment]
now that I posted, I see that especially the purple ones are not very legible. Maybe a colour change would do aswell.

**Comment by PatrickDeVries** [comment]
I'll investigate styling them more nicely when I get a chance. In the meantime the colors are configurable in the plugin settings, so you should be able to tweak it to be workable for now.
